nodeLinker: node-modules

packageExtensions:
  "@instructure/console@8":
    peerDependenciesMeta:
      "react":
        optional: true
  "@instructure/shared-types@8":
    peerDependenciesMeta:
      "react":
        optional: true
  "@instructure/ui-utils@8":
    peerDependenciesMeta:
      "react":
        optional: true
      "react-dom":
        optional: true
